$themePalette = @{
    themePrimary = "#042ca2"            # New Primary Color - Deep Blue
    themeLighterAlt = "#f6f9fd"         # Very Light Variant of Primary
    themeLighter = "#e0e7f8"            # Lighter Variant of Primary
    themeLight = "#b8c9f1"              # Light Variant of Primary
    themeTertiary = "#7294e3"           # Tertiary Color based on Primary
    themeSecondary = "#4b67d6"          # Secondary Color
    themeDarkAlt = "#3c2691"            # Dark Alternative of Primary
    themeDark = "#2e1f6e"               # Dark Variant of Primary
    themeDarker = "#221851"             # Darkest Variant of Primary
    neutralLighterAlt = "#faf9f8"       # Light Neutral
    neutralLighter = "#f3f2f1"          # Lighter Neutral
    neutralLight = "#edebe9"            # Neutral Light
    neutralQuaternaryAlt = "#e1dfdd"    # Alternate Neutral Quaternary
    neutralQuaternary = "#d0d0d0"       # Neutral Quaternary
    neutralTertiaryAlt = "#c8c6c4"      # Alternate Neutral Tertiary
    neutralTertiary = "#a19f9d"         # Neutral Tertiary
    neutralSecondaryAlt = "#8a8886"     # Alternate Neutral Secondary
    neutralSecondary = "#605e5c"        # Neutral Secondary
    neutralPrimaryAlt = "#3b3a39"       # Almost Black, for strong text
    neutralPrimary = "#323130"          # Nearly Black, for primary text
    neutralDark = "#201f1e"             # Dark Neutral
    black = "#000000"                   # Black
    white = "#ffffff"                   # White
    primaryBackground = "#ffffff"       # Primary Background
    primaryText = "#323130"             # Primary Text
    accent = "#FDB940"                  # Accent Color - Orange-Yellow
    error = "#DF6D27"                   # Error Color - Burnt Orange
}
